apiVersion: apps/v1
kind: Deployment
metadata:
  name: file
  labels:
    app: file
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
        tier: backend
    spec:
      containers:
      - name: file
        image: "ghcr.io/vcc-chat/vcc_rpc"
        command: ["/usr/local/bin/python3.11","/app/services/file.py"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: RPCHOST
            value: "rpcserver:2474"
          - name: MINIO_SSL
            value: "1"
          - name: MINIO_URL
            valueFrom:
              secretKeyRef:
                name: minio-url
                key: password
          - name: MINIO_ACCESS
            valueFrom:
              secretKeyRef:
                name: minio-access
                key: password
          - name: MINIO_SECRET
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: password
          - name: FILE_BUCKET_PREFIX
            valueFrom:
              secretKeyRef:
                name: file-bucket-prefix
                key: prefix
