apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth_github
  labels:
    app: oauth_github
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth_github
  template:
    metadata:
      labels:
        app: oauth_github
        tier: backend
    spec:
      containers:
      - name: oauth_github
        image: "ghcr.io/vcc-chat/vcc_rpc"
        command: ["/usr/local/bin/python3.11","/app/services/oauth_github.py"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: RPCHOST
            value: "rpcserver:2474"
          - name: VCC_DOMAIN
            valueFrom:
              configMapRef:
                name: vcc-domain
                key: domain
          - name: GH_CLIENTID
            valueFrom:
              secretKeyRef:
                name: github-oauth
                key: id
          - name: GH_CLIENTSEC
            valueFrom:
              secretKeyRef:
                name: github-oauth
                key: secret
          - name: GH_CALLBACKURL
            valueFrom:
              secretKeyRef:
                name: github-oauth
                key: clientid
          - name: GH_CALLBACKURL
            value: "https://$(VCC_DOMAIN)/oauth/github"
          - name: HTTP_PORT
            value: "8888"
---
apiVersion: v1
kind: Service
metadata:
  name: oauth_github
  labels:
    app: oauth_github
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: oauth_github
    tier: backend
